eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
